Add GO build rules
unikraft/lib-libgo pull request #2
Opened 2021-07-29 12:34 UTC by vladandrew

Our recent patch moves the GO build rules outside the main Unikraft
repo.

Signed-off-by: Vlad-Andrei Badoiu <vlad_andrei.badoiu@upb.ro>

2021-07-29 20:17 UTC, skuenzer approved these changes
Looks good to me. Thanks!

Reviewed-by: Simon skuenzer <simon.kuenzer@neclab.eu>

2021-11-06 18:44 UTC, razvand requested changes
All good.

Reviewed-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

2021-11-06 18:45 UTC, razvand approved these changes

2021-11-27 13:42 UTC, razvand commented
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

2021-11-27 18:28 UTC, closed without merging