Upgrade Go to 1.18
unikraft/lib-libgo pull request #7
Opened 2023-07-26 13:00 UTC by eduardvintila

2023-08-05 17:58 UTC, StefanJum commented
@eduardvintila What gccgo version should we use? I'm using `gccgo-11` and I get the following error
```
workdir/apps/helloworld-go/build/libgo/origin/gcc-12.1.0/libgo/go/internal/abi/abi.go:20:19: error: use of undefined type ‘any’                                   
   20 | func FuncPCABI0(f any) uintptr { 
```
All prs mentioned in the description are merged.

2023-08-05 19:49 UTC, eduardvintila commented
> What gccgo version should we use?

@StefanJum, you should use version 12, as stated in the description (though indeed I did not mention explicitly `gccgo`, I'll have to edit that).

2023-08-06 15:50 UTC, eduardvintila commented
I've updated the documentation.

2023-08-06 17:30 UTC, StefanJum reviewed
@eduardvintila new issue, any idea on this one?
```
CRITICAL:root:2
workdir/libs/libgo/Makefile.build:3: workdir/apps/helloworld-go/build/go/apphelloworldgo/Makefile: No such file or directory
make[3]: *** No rule to make target 'workdir/apps/helloworld-go/build/go/apphelloworldgo/Makefile'.  Stop.
```

2023-08-06 17:33 UTC, eduardvintila commented
@StefanJum hmm, did you also update `app-helloworld-go`?

2023-08-06 17:46 UTC, StefanJum commented
> @StefanJum hmm, did you also update `app-helloworld-go`?

Yes, it's weird, I've built it in a docker container and everything builds and runs fine, but if I try to build locally it fails.
It might be some version stuff, I'll keep looking.

2023-08-06 18:45 UTC, razvand commented
@StefanJum , you need `golang` package installed.

2023-08-06 19:42 UTC, RaduNichita requested changes
Nice work, @eduardvintila 

I have a question: could we reduce the number of files modified by this PR by not including the autogenerated files and generating them on the fly?

2023-08-06 19:42 UTC, RaduNichita commented on libgo/libcalls.go
> +// Code generated by mksyscall.awk. DO NOT EDIT.
If this file was automatically generated, could we add a rule in the makefile for that generating it of including it per se?

2023-08-06 19:42 UTC, RaduNichita commented on libgo/Makefile.runtime.uk
> +# This file has been auto-generated for go1.18 gccgo (GCC) 12.1.0.
Same here

2023-08-06 19:58 UTC, eduardvintila commented on libgo/libcalls.go
> +// Code generated by mksyscall.awk. DO NOT EDIT.
`mksyscall.awk` is from the upstream `gcc` build system. It's not integrated with Unikraft, and I don't see an easy way to add a rule in the Makefile for the moment. Ofc it would be ideal if we could automate this, but I don't think it's feasible for this release :).

2023-08-06 20:01 UTC, eduardvintila commented on libgo/Makefile.runtime.uk
> +# This file has been auto-generated for go1.18 gccgo (GCC) 12.1.0.
This one is generated by the helper scripts, found in the `scripts/` directory (also introduced with this PR). In a similar manner, `lib-musl` also includes generated Makefiles for each component (i.e. [Makefile.uk.musl.complex](https://github.com/unikraft/lib-musl/blob/staging/Makefile.uk.musl.complex), [Makefile.uk.musl.signal](https://github.com/unikraft/lib-musl/blob/staging/Makefile.uk.musl.signal) etc.), providing also helper scripts to generate them. So I think we should keep this approach for consistency.

2023-08-06 20:08 UTC, RaduNichita commented on libgo/libcalls.go
> +// Code generated by mksyscall.awk. DO NOT EDIT.
Ok, let's stick with this. Maybe you should open a issue regarding this so we don't lose it in the comments.

2023-08-07 14:35 UTC, RaduNichita approved these changes
Nice work, @eduardvintila 

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-08-07 16:06 UTC, StefanJum reviewed
@eduardvintila everything seems to work fine.

One comment I have it's that everything is done very `x86`-targeted (i.e. adding `-D__x86_64__`, `x86` headers and source files, setting `x86` in config files, etc.), and this might be an issue if we want to add arm support in the future.
We tried (with @razvand) to compile this for arm and we eventually made it to the linking step, but I would make everything that is architecture specific depend on `$(ARCH)` being set to `x86_64`.

2023-08-07 16:30 UTC, razvand commented
@StefanJum, @eduardvintila, we will have only x86_64 for Go this release. I had made progress with the AArch64 part, but it requires further work. We'll do it after the release and have a sub-release with Go support for AArch64.

2023-08-08 08:13 UTC, eduardvintila commented
@StefanJum, you're right. I've refactored the makefiles and some source files to emphasize which parts are architecture dependent.

@razvand, for an ARM build to work, the `ukvmem` library is necessary, which is not yet adapted to `aarch64`.

2023-08-08 14:35 UTC, StefanJum commented
One more thing @eduardvintila, I think we should add compiler version checks in the `Makefile.uk` (similar to what we have in the Unikraft [`Makefile`](https://github.com/unikraft/unikraft/blob/staging/Makefile#L693)). I think it's the best way to document the minimum required compiler version.

2023-08-10 20:53 UTC, eduardvintila commented
Thank you, @StefanJum - I've included your suggestion! Also updated the PR based on the changes introduced by [this commit](https://github.com/unikraft/unikraft/commit/b8872a6b572cf784880766906cf707ef13851c54) from Unikraft core.

2023-08-11 08:04 UTC, StefanJum commented
@eduardvintila I get these errors, I remember I've got them before but I can't figure out what I did to get pass them.

```
/home/unikraft/SJ/maintainer-tools/workdir/apps/helloworld-go/build/libsyscall_shim/uk_syscall_r_fn.c:321:9: error: duplicate case value                                                                           
  321 |         case SYS_madvise:                                                                                                                                                                                  
      |         ^~~~                                                                                     
/home/unikraft/SJ/maintainer-tools/workdir/apps/helloworld-go/build/libsyscall_shim/uk_syscall_r_fn.c:81:9: note: previously used here                                                                             
   81 |         case SYS_madvise:                                                                                                                                                                                  
      |         ^~~~             
/home/unikraft/SJ/maintainer-tools/workdir/apps/helloworld-go/build/libsyscall_shim/uk_syscall_r_fn.c:331:9: error: duplicate case value                                                                           
  331 |         case SYS_mprotect:                                                                                                                                                                                 
      |         ^~~~                                                                                                                                                                                               
/home/unikraft/SJ/maintainer-tools/workdir/apps/helloworld-go/build/libsyscall_shim/uk_syscall_r_fn.c:76:9: note: previously used here                                                                             
   76 |         case SYS_mprotect:  
```

2023-08-11 11:16 UTC, eduardvintila commented
> @eduardvintila I get these errors, I remember I've got them before but I can't figure out what I did to get pass them.
> 
> ```
> /home/unikraft/SJ/maintainer-tools/workdir/apps/helloworld-go/build/libsyscall_shim/uk_syscall_r_fn.c:321:9: error: duplicate case value                                                                           
>   321 |         case SYS_madvise:                                                                                                                                                                                  
>       |         ^~~~                                                                                     
> /home/unikraft/SJ/maintainer-tools/workdir/apps/helloworld-go/build/libsyscall_shim/uk_syscall_r_fn.c:81:9: note: previously used here                                                                             
>    81 |         case SYS_madvise:                                                                                                                                                                                  
>       |         ^~~~             
> /home/unikraft/SJ/maintainer-tools/workdir/apps/helloworld-go/build/libsyscall_shim/uk_syscall_r_fn.c:331:9: error: duplicate case value                                                                           
>   331 |         case SYS_mprotect:                                                                                                                                                                                 
>       |         ^~~~                                                                                                                                                                                               
> /home/unikraft/SJ/maintainer-tools/workdir/apps/helloworld-go/build/libsyscall_shim/uk_syscall_r_fn.c:76:9: note: previously used here                                                                             
>    76 |         case SYS_mprotect:  
> ```
> 
> Any unmerged pr that I need or some extra config options?

Nope, no additional PR is needed. It looks like the same syscalls are provided by two seperate libraries. By any chance, do you have both `ukmmap` and `posix-mmap` selected? This obviously should not happen, but sometimes it's influenced by the order in which you select libraries... :(

2023-08-11 11:24 UTC, StefanJum commented
> @StefanJum Nope, no additional PR is needed. It looks like the same syscalls are provided by two seperate libraries. By any chance, do you have both `ukmmap` and `posix-mmap` selected? This obviously should not happen, but sometimes it's influenced by the order in which you select the libraries... However, [this commit](https://github.com/unikraft/unikraft/commit/5c4201247095bd7b17d3c31898ca7a6f62f6afdd) should've solved the problem; I did not encounter it after it was merged

Yes, that was it. It's really messed up, it was selected even if it did not show up in the config menu (due to the `depends on` statement). I had to unselect everything and get it to show up, deselect it end select everything else again :smiling_face_with_tear:

2023-08-11 11:25 UTC, StefanJum approved these changes
Anyway this works, we need to soon get rid of `ukmmap` tho.
Thanks a lot for the work @eduardvintila :tada: :tada:

2023-08-11 11:52 UTC, StefanJum approved these changes
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-08-11 12:14 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-08-11 16:12 UTC, closed without merging